---
# DON'T USE ANSIBLE TO CONTROL ASG INSTANCES
# Instead: use Ansible to create the ASG and specify the user data
- hosts: tag_Module_5
  user: ec2-user
  become: true
  vars:
    ansible_python_interpreter: /usr/bin/python
  tasks:
    - name: Install emacs
      package:
        name: emacs-nox
        state: present
- hosts: tag_Department_Developer
  user: ec2-user
  become: true
  vars:
    ansible_python_interpreter: /usr/bin/python
  tasks:
    - name: Remove nano
      package:
        name: nano
        state: absent